Issue 22 base tests
Hydra-Chain/hydragon-core-contracts pull request #25
Opened 2024-01-02 07:33 UTC by Vitomir2

* add more ValidatorSet tests and create new System tests;
* make some fixes in the contracts - change names, add imports and other minor bugs;
* rename VestingLib -> VestingPositionLib and RewardPoolContract -> RewardPool;
* create new methods - getValidator, getEpochByBlock and getSortedValidators;

2024-01-03 10:31 UTC, R-Santev requested changes
Overal looks amazing. There are just a few things to be improved and added.

2024-01-03 10:31 UTC, R-Santev commented on test/Hydra/ValidatorSet/ValidatorSet.test.ts
> +      const { validatorSet } = await loadFixture(this.fixtures.commitEpochTxFixture);
Sorted validators can be replaced with simpler function that only get all active validators without sort

2024-01-03 10:31 UTC, R-Santev commented on test/Hydra/mochaContext.ts
> +export function initValidators(accounts: SignerWithAddress[], from: number = 0, to: number = 4) {
why is this function declared in the mochaContext file?

2024-01-03 10:31 UTC, R-Santev commented on test/Hydra/ValidatorSet/Staking.test.ts
> +}
Tests for vested staking are not implemented

2024-01-03 10:31 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Staking/IStaking.sol
> +    function sortedValidators(uint256 n) external view returns (address[] memory);
Replace with just active validators. Ping me for more information.

2024-01-04 06:47 UTC, Vitomir2 commented on test/Hydra/ValidatorSet/ValidatorSet.test.ts
> +      // TODO: vito.do: read about erc20vote and how it works. Its delegate works differently from our delegate. Then, I will know why totalSupplyAt returns 0
What do you mean by "fix" test ?

2024-01-04 07:20 UTC, Vitomir2 commented on test/Hydra/mochaContext.ts
> +export function initValidators(accounts: SignerWithAddress[], from: number = 0, to: number = 4) {
I had to move it into the helper. Will do.

2024-01-08 13:23 UTC, Vitomir2 commented on test/Hydra/ValidatorSet/ValidatorSet.test.ts
> +      // TODO: vito.do: read about erc20vote and how it works. Its delegate works differently from our delegate. Then, I will know why totalSupplyAt returns 0
done

2024-01-08 13:26 UTC, Vitomir2 commented
Fixed everything related to the comments and even added some stuff to the contracts.

* add the getValidators method to retrieve all the available validators;
* create a new flag for the validator to check when it is registered or not and throw custom error when the validator is already registered;
* add tests for the new method and error that it could throw;
* create new helper methods - registerValidator, findProperRPSIndex, and update the helper that commits multiple epochs;
* adapt the vested staking tests;
* re-arrange the arguments to match the parameters when calling  _calculateValidatorAndDelegatorShares;
* fix typo veting -> vesting;
* delete unused commented code;

2024-01-08 15:35 UTC, R-Santev requested changes

2024-01-08 15:35 UTC, R-Santev commented on test/Hydra/ValidatorSet/Staking.test.ts
> +          value: this.minDelegation,
minDelegation is used for stake action. Maybe better to create a minStake variable?

2024-01-08 15:35 UTC, R-Santev commented on test/Hydra/ValidatorSet/Staking.test.ts
> +        if (!tx.blockNumber) {
There is no need of blockNumber checks in my opinion.

2024-01-08 15:35 UTC, R-Santev commented on test/Hydra/ValidatorSet/ValidatorSet.test.ts
> +    it("should all active validators - admin", async function () {
"get" is missed?

2024-01-08 16:00 UTC, Vitomir2 commented
Resolved all the remarks.

2024-01-08 16:06 UTC, R-Santev approved these changes

2024-01-09 06:22 UTC, merged