Issue 24 delegation tests
Hydra-Chain/hydragon-core-contracts pull request #28
Opened 2024-01-22 20:06 UTC by Vitomir2

* re-write the delegation methods and functionality that has left;
* optimize the code structure in some of the contracts;
* rename VestingData -> Vesting and DelegationVesting -> VestedDelegation;
* add some missings and implement all the delegation, and vested delegation, tests;

2024-01-30 14:22 UTC, R-Santev requested changes

2024-01-30 14:22 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Staking/BalanceState.sol
> +contract BalanceState {
StakingData?

2024-01-30 14:22 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Delegation/Delegation.sol
> +// import "@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC20VotesUpgradeable.sol";
Remove commented code

2024-01-30 14:22 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Delegation/IDelegation.sol
>       * @notice Delegates sent amount to validator. Claims rewards beforehand.
Does it claim rewards beforehand currently?

2024-01-30 14:22 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Delegation/IDelegation.sol
> +    function claimPositionReward(address validator, uint256 epochNumber, uint256 topUpIndex) external;
Rewards claiming must be part of the RewardPool contract

2024-01-30 14:22 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Delegation/Delegation.sol
> +    function delegateToValidator(address validator) public payable {
it is clear that the delegate would be to validator, so delegate is enough as name

2024-01-30 14:22 UTC, R-Santev commented on contracts/Hydra/ValidatorSet/modules/Delegation/Delegation.sol
> +    function claimPositionReward(address validator, uint256 epochNumber, uint256 topUpIndex) external onlyManager {
Must be part of the reward pool

2024-02-01 10:18 UTC, Vitomir2 commented on contracts/child/LiquidityToken.sol
This is the LiquidityToken contract from the old contracts, as you can see, it is in the `contracts/child` directory, but we have it in the `contracts/Hydra/LiquidityToken` directory already.

2024-02-01 10:31 UTC, Vitomir2 commented on contracts/Hydra/ValidatorSet/modules/Delegation/IDelegation.sol
> +    function claimPositionReward(address validator, uint256 epochNumber, uint256 topUpIndex) external;
Well, I will then have to create a function to registerWithdrawal that will be public, otherwise, how am I going to be able to register a withdraw?

2024-02-02 15:32 UTC, Vitomir2 commented
Finalized the contract changes, only some tests left to optimize and for now I skipped them. I will finalize later on. @R-Santev

2024-02-09 09:27 UTC, R-Santev approved these changes

2024-02-09 09:44 UTC, merged