Modify faucet
Hydra-Chain/hydragon-core-contracts pull request #29
Opened 2024-01-24 10:15 UTC by Vitomir2

2024-01-30 08:36 UTC, R-Santev requested changes

2024-01-30 08:36 UTC, R-Santev commented on contracts/child/Faucet.sol
>          require(sent, "Failed to send Ether");
Better use if with custom error here for gas optimization (Please compare the gas costs and share with me so I can know what the impact is)

2024-01-30 08:57 UTC, Vitomir2 commented on contracts/child/Faucet.sol
>          require(sent, "Failed to send Ether");
`require`
*OnSuccess:*
- gas: 71864
- tx cost: 62490
- exec cost: 41058

*OnFail:*
- gas: 3000000
- tx cost: 61085
- exec cost: 39653

`revert`
*OnSuccess:*
- gas: 71864
- tx cost: 62490
- exec cost: 41058

*OnFail:*
- gas: 3000000
- tx cost: 61138
- exec cost: 39706

2024-01-30 09:29 UTC, Vitomir2 commented on contracts/child/Faucet.sol
>          require(sent, "Failed to send Ether");
Done @R-Santev

2024-01-30 11:56 UTC, R-Santev requested changes
A few more minor changes are needed

2024-01-30 11:56 UTC, R-Santev commented on contracts/child/Faucet.sol
> +        if (block.timestamp <= nextAccessTime[account]) revert InsufficientCooldown();
Using <= is more expensive than using <

2024-01-30 11:56 UTC, R-Santev commented on contracts/interfaces/Errors.sol
> +error ZeroAddress();
These errors are specific to the Faucet contract so they can live there

2024-02-02 15:42 UTC, Vitomir2 commented on contracts/interfaces/Errors.sol
> +error ZeroAddress();
I think two of the errors can be left here - `ZeroAddress` and `SendFailed`, because they can be reused in multiple places, imo.

I will move only the `InsufficientCooldown`

2024-02-05 10:33 UTC, R-Santev approved these changes

2024-02-05 10:41 UTC, merged