173 i need a price module in the aprcalculator contract to calculate an average price for the latest 24 hours
Hydra-Chain/hydragon-core-contracts pull request #47
Opened 2024-07-26 12:11 UTC by SamBorisov

Price module
1 - in each epoch, we can quote the price
2 - after a day, we update the price

2024-07-29 10:24 UTC, Vitomir2 requested changes
Overall looks good, but there are some small changes to be made, imo.

2024-07-29 10:24 UTC, Vitomir2 commented on contracts/APRCalculator/modules/Price/Price.sol
> +            _updatePrice();
We have to decide what price to initialize, because on the first day it will be 0.

2024-07-29 11:59 UTC, Vitomir2 approved these changes

2024-07-31 11:06 UTC, R-Santev approved these changes

2024-07-31 11:19 UTC, merged