Sort price v2
Hydra-Chain/hydragon-core-contracts pull request #60
Opened 2024-09-03 14:35 UTC by SamBorisov

Add PriceGroupsLib, for simplicity and efficiency in voting
Added tests for it, and mock test that is skipped (it takes too long but good for testing gas)

2024-09-09 08:43 UTC, R-Santev requested changes

2024-09-09 08:43 UTC, R-Santev commented on contracts/PriceOracle/PriceOracle.sol
> +        uint256 groupLength = priceGroups.groups.length;
```suggestion
        uint256 groupsLength = priceGroups.groups.length;
```

2024-09-09 08:43 UTC, R-Santev commented on contracts/PriceOracle/libs/PriceGroupsLib.sol
> +        // assert(validator != address(0)); // This is not needed, as the validator is the msg.sender, who should always be a valid address
you can't be sure address zero will never be the caller

2024-09-09 08:43 UTC, R-Santev commented on contracts/PriceOracle/libs/PriceGroupsLib.sol
> +        // assert(price != 0);  // This is not needed, as the price is already checked in the calling function
decide where to add the check

2024-09-09 08:43 UTC, R-Santev commented on contracts/PriceOracle/libs/PriceGroupsLib.sol
> +        /// @dev We cannot check if the validator is already in the group, so make sure to check if validator already voted this before calling the function (in our case, this is done in the vote fun
move this comment above the function declaration so it will be added to the NatSpec generated docs

2024-09-09 08:43 UTC, R-Santev commented on contracts/PriceOracle/libs/PriceGroupsLib.sol
> +            self.votedValidators++; // Max validators in our case is 150, so no need to check for overflow
better calculate votedValidators when iterating through the groups on calculating quorum, so you can ensure there are at least 4 active validators voted

2024-09-09 08:43 UTC, R-Santev commented on test/forge/libs/PriceGroups.t.sol
> +
Add concrete test cases

2024-09-10 09:01 UTC, R-Santev requested changes

2024-09-10 09:01 UTC, R-Santev commented on contracts/PriceOracle/libs/PriceGroupsLib.sol
> +        }
leave an empty line before return

2024-09-13 12:15 UTC, SamBorisov commented
Since calculating the average price works with the sum of all votes in the group, but some of the votes can be from ex-validators and we cannot get the exact average price for the group for only currently active validators, we will resume with a listing library!

2024-09-13 12:15 UTC, closed without merging